####### Configuration file of Jail #######

### Restrictions of prisoners ###
allow-chat: true
allow-command: false
allow-block-break: false
allow-block-place: false
#If false, restricts player's VECTOR3 movement, not whole POSITION
allow-movement: true
allow-attack: false
disable-damage: true

default-lang: en

### Settings ###
#Count when the prisoner is offline?
offline-time-counting: true
#Enable additional penalty when players try to destroy the jail?
enable-penalty: true
#How much time to be added to that player as penalty? (minutes)
penalty-time: 10
#Allow players to bail using money?
allow-bail: true
#How much money per second a player has to pay to bail?
bail-per-second: 100
#OPs can't be jailed?
op-can-be-jailed: true
#Enable Server-start latest version tracker?
updater-start-fetch: true
#Enable auto latest version installation?
updater-auto-install: true
#Enable frequent scheduled auto update checker?
scheduled-update-checker: true
#Minutes between each check? (Ignore if scheduled-update-checker=false)
scheduled-update-checker-interval: 45

### Config version ###
#Do not modify this, otherwise plugin may not work properly
v: Alpha0.1.1